Repository project-akri/akri, pull requests merged in 2020-12, with the labels that each got.

#160 Update user guide with first release tag for Akri release chart
  docs/customizing-akri-installation.md
  docs/end-to-end-demo-rpi4.md
  docs/end-to-end-demo.md
  docs/onvif-configuration.md
  docs/requesting-akri-resources.md
  docs/udev-configuration.md
  docs/udev-video-sample.md
  docs/user-guide.md
Labels: documentation

#152 OPC UA Discovery Handler
  .dockerignore
  .github/workflows/build-anomaly-detection-app-container.yml
  .github/workflows/build-opcua-monitoring-broker-container.yml
  Cargo.lock
  README.md
  agent/Cargo.toml
  agent/src/protocols/mod.rs
  agent/src/protocols/opcua/discovery_handler.rs
  agent/src/protocols/opcua/discovery_impl.rs
  agent/src/protocols/opcua/mod.rs
  build/akri-containers.mk
  build/containers/Dockerfile.anomaly-detection-app
  build/containers/Dockerfile.opcua-monitoring-broker
  controller/Cargo.toml
  deployment/helm/Chart.yaml
  deployment/helm/crds/akri-configuration-crd.yaml
  deployment/helm/templates/opcua.yaml
  deployment/helm/values.yaml
  deployment/samples/akri-anomaly-detection-app.yaml
  docs/customizing-akri-installation.md
  docs/development.md
  docs/media/akri-architecture.svg
  docs/media/opcua-certificates-diagram.svg
  docs/media/opcua-demo-diagram.svg
  docs/opcua-configuration.md
  docs/opcua-demo.md
  docs/roadmap.md
  docs/user-guide.md
  samples/apps/anomaly-detection-app/anomaly_detection.py
  samples/apps/anomaly-detection-app/data.csv
  samples/apps/anomaly-detection-app/generategrpc.sh
  samples/apps/anomaly-detection-app/opcua_node_pb2.py
  samples/apps/anomaly-detection-app/opcua_node_pb2_grpc.py
  samples/apps/anomaly-detection-app/templates/index.html
  samples/brokers/opcua-monitoring-broker/Program.cs
  samples/brokers/opcua-monitoring-broker/Properties/launchSettings.json
  samples/brokers/opcua-monitoring-broker/Startup.cs
  samples/brokers/opcua-monitoring-broker/appsettings.Development.json
  samples/brokers/opcua-monitoring-broker/appsettings.json
  samples/brokers/opcua-monitoring-broker/opcua-monitoring-broker.csproj
  samples/brokers/opcua-monitoring-broker/opcua_node.proto
  samples/brokers/udev-video-broker/Cargo.toml
  samples/opcua-certificate-generator/Program.cs
  samples/opcua-certificate-generator/README.md
  samples/opcua-certificate-generator/opcua-certificate-generator.csproj
  shared/Cargo.toml
  shared/src/akri/configuration.rs
  test/yaml/akri-opcua.yaml
  version.sh
  version.txt
Labels: enhancement

#169 Add Deployment-based deployment strategy
  docs/proposals/broker-deployment-strategies.md
Labels: documentation, enhancement

#167 Use new http protocol in extensibility documentation
  docs/extensibility.md
Labels: documentation

#162 Proposal zeroconf
  docs/proposals/zeroconf.md
Labels: documentation

#150 security proposal
  docs/media/akri-threat-model.png
  docs/proposals/security.md
Labels: documentation
