Repository project-akri/akri, pull requests merged in 2021-09, with the labels that each got.

#371 [SAME VERSION] Enable stale action
  .github/workflows/stale-tasks.yml
Labels: same version

#380 add CODEOWNERS file
  .github/workflows/check-versioning.yml
  CODEOWNERS
Labels: documentation

#382 ONVIF Discovery Handler - Handle Multicast Response Duplicates
  Cargo.lock
  agent/Cargo.toml
  controller/Cargo.toml
  deployment/helm/Chart.yaml
  discovery-handler-modules/debug-echo-discovery-handler/Cargo.toml
  discovery-handler-modules/onvif-discovery-handler/Cargo.toml
  discovery-handler-modules/opcua-discovery-handler/Cargo.toml
  discovery-handler-modules/udev-discovery-handler/Cargo.toml
  discovery-handlers/debug-echo/Cargo.toml
  discovery-handlers/onvif/Cargo.toml
  discovery-handlers/onvif/src/discovery_impl.rs
  discovery-handlers/opcua/Cargo.toml
  discovery-handlers/udev/Cargo.toml
  discovery-utils/Cargo.toml
  samples/brokers/udev-video-broker/Cargo.toml
  shared/Cargo.toml
  version.txt
  webhooks/validating/configuration/Cargo.toml
Labels: bug

#385 Make Discovery Handlers check channel health each discovery loop
  Cargo.lock
  agent/Cargo.toml
  controller/Cargo.toml
  deployment/helm/Chart.yaml
  discovery-handler-modules/debug-echo-discovery-handler/Cargo.toml
  discovery-handler-modules/onvif-discovery-handler/Cargo.toml
  discovery-handler-modules/opcua-discovery-handler/Cargo.toml
  discovery-handler-modules/udev-discovery-handler/Cargo.toml
  discovery-handlers/debug-echo/Cargo.toml
  discovery-handlers/debug-echo/src/discovery_handler.rs
  discovery-handlers/onvif/Cargo.toml
  discovery-handlers/onvif/src/discovery_handler.rs
  discovery-handlers/opcua/Cargo.toml
  discovery-handlers/opcua/src/discovery_handler.rs
  discovery-handlers/udev/Cargo.toml
  discovery-handlers/udev/src/discovery_handler.rs
  discovery-utils/Cargo.toml
  samples/brokers/udev-video-broker/Cargo.toml
  shared/Cargo.toml
  version.txt
  webhooks/validating/configuration/Cargo.toml
Labels: bug

#388 Add K3s version 1.21.5 to test cases matrix [SAME VERSION]
  .github/workflows/run-test-cases.yml
Labels: bug

#389 Add READMEs to Akri's non-core components
  samples/apps/anomaly-detection-app/README.md
  samples/apps/video-streaming-app/README.md
  samples/brokers/onvif-video-broker/README.md
  samples/brokers/opcua-monitoring-broker/README.md
  samples/brokers/udev-video-broker/README.md
  samples/opcua-certificate-generator/README.md
Labels: documentation

#392 Add release v0.6.19 notes to CHANGELOG
  CHANGELOG.md
Labels: documentation

#393 Fix how duplicates are handled in ONVIF [SAME VERSION]
  discovery-handlers/onvif/src/discovery_impl.rs
Labels: bug

#394 Update `v0.6.19` CHANGELOG with known issue
  CHANGELOG.md
Labels: documentation
