Repository project-akri/akri, pull requests merged in 2021-11, with the labels that each got.

#417 Fix nits in CODE_OF_CONDUCT and GOVERNANCE
  CODE_OF_CONDUCT.md
  GOVERNANCE.md
Labels: documentation

#419 Make debug echo capacity configurable
  Cargo.lock
  agent/Cargo.toml
  controller/Cargo.toml
  deployment/helm/Chart.yaml
  deployment/helm/templates/debug-echo-configuration.yaml
  deployment/helm/values.yaml
  discovery-handler-modules/debug-echo-discovery-handler/Cargo.toml
  discovery-handler-modules/onvif-discovery-handler/Cargo.toml
  discovery-handler-modules/opcua-discovery-handler/Cargo.toml
  discovery-handler-modules/udev-discovery-handler/Cargo.toml
  discovery-handlers/debug-echo/Cargo.toml
  discovery-handlers/onvif/Cargo.toml
  discovery-handlers/opcua/Cargo.toml
  discovery-handlers/udev/Cargo.toml
  discovery-utils/Cargo.toml
  samples/brokers/udev-video-broker/Cargo.toml
  shared/Cargo.toml
  version.txt
  webhooks/validating/configuration/Cargo.toml
Labels: bug

#420 Return okay if get 404 when trying to delete an Instance
  Cargo.lock
  agent/Cargo.toml
  controller/Cargo.toml
  deployment/helm/Chart.yaml
  discovery-handler-modules/debug-echo-discovery-handler/Cargo.toml
  discovery-handler-modules/onvif-discovery-handler/Cargo.toml
  discovery-handler-modules/opcua-discovery-handler/Cargo.toml
  discovery-handler-modules/udev-discovery-handler/Cargo.toml
  discovery-handlers/debug-echo/Cargo.toml
  discovery-handlers/onvif/Cargo.toml
  discovery-handlers/opcua/Cargo.toml
  discovery-handlers/udev/Cargo.toml
  discovery-utils/Cargo.toml
  samples/brokers/udev-video-broker/Cargo.toml
  shared/Cargo.toml
  shared/src/k8s/mod.rs
  version.txt
  webhooks/validating/configuration/Cargo.toml
Labels: bug

#430 Install appropriate crictl package based on platform [SAME VERSION]
  build/containers/Dockerfile.agent
  build/containers/Dockerfile.agent-full
Labels: bug

#426 Execute workloads based on labels instead of flags in PR titles
  .github/pull_request_template.md
  .github/workflows/build-opencv-base-container.yml
  .github/workflows/build-rust-crossbuild-container.yml
  .github/workflows/check-versioning.yml
Labels: same version
